// Generated by `bun init`

// ReadableStream is async-iterable at runtime (WHATWG spec) but TS's lib.dom.d.ts
// doesn't declare it yet — add the missing symbol so `for await...of` compiles.
interface ReadableStream<R = any> {
	[Symbol.asyncIterator](): AsyncIterator<R>;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
